module.exports = {
  SUCCESS_CODE: 'SUCCESS',
  INTERNAL_CODE: 'INTERNAL_ERROR',
  LOGIN_ERROR_CODE: 'LOGIN_ERROR',
  NOT_FOUND_CODE: 'RESOURCE_NOT_FOUND',
  DATABASE_ERROR_CODE: 'DATABASE_ERROR',
  COINGECKO_ERROR_CODE: 'COINGECKO_ERROR',
  VALIDATION_ERROR_CODE: 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR_CODE: 'AUTHORIZATION_ERROR'
};
