module.exports = {
  SUCCESS_CODE: 'SUCCESS',
  INTERNAL_CODE: 'INTERNAL_ERROR',
  NOT_FOUND_CODE: 'RESOURCE_NOT_FOUND',
  DATABASE_ERROR_CODE: 'DATABASE_ERROR',
  VALIDATION_ERROR_CODE: 'VALIDATION_ERROR'
};
